name: Docker Image CI

on:
  release:
    types: [published]

jobs:
  buildimage:
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        node-version: [19.0.x]
    steps:
      - uses: actions/checkout@v2
      - name: Get the version
        id: vars
        run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})

      # Setup gcloud CLI
      - uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_key: ${{ secrets.GCR_DEVOPS_SERVICE_ACCOUNT_KEY }}
          project_id: ${{ secrets.PROJECT_ID }}
          export_default_credentials: true

      # Configure docker to use the gcloud command-line tool as a credential helper
      - run: |
          gcloud auth configure-docker -q

      - name: Build Source
        run: |
          npm install
          npm run build --if-present

      - name: Build chatgpt-slackbot image
        run: docker build . --file Dockerfile --tag gcr.io/lil-com/deepext-chatgpt-slackbot:${{steps.vars.outputs.tag}}

      - name: Push chatgpt-slackbot image
        run: |-
          docker push gcr.io/lil-com/deepext-chatgpt-slackbotr:${{steps.vars.outputs.tag}}
